spring:
  mvc:
    favicon:
      enabled: false
  application:
    name: delilah

  jackson:
    property-naming-strategy: SNAKE_CASE

  cloud:
    consul:
      host: 192.168.10.229
      port: 8500

swagger:
  enable: true

mybatis:
  config-location: classpath:mybatis-dev.xml
  mapper-locations: classpath:mapper/**/*.xml

sharding:
  jdbc:
    config:
      masterslave:
        name: m1s1
        master-data-source-name: master
        slave-data-source-names: slave0
      props:
        sql:
          show: true
        cpu:
          size: 2
        load-balance-algorithm-type: round_robin

    datasource:
      names: master,slave0
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.10.229:3306/im?useSSL=false&amp;useUnicode=true&amp;serverTimezone=UTC&amp;characterEncoding=UTF-8&amp;autoReconnect=true
        username: imtest
        password: 123456
        test-on-borrow: false
        test-while-idle: true
        validation-query: SELECT 1
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 30000
        connection-init-sqls: set names utf8mb4;
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.10.229:3306/im?useSSL=false&amp;useUnicode=true&amp;serverTimezone=UTC&amp;characterEncoding=UTF-8&amp;autoReconnect=true
        username: imtest
        password: 123456
        test-on-borrow: false
        test-while-idle: true
        validation-query: SELECT 1
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 30000
        connection-init-sqls: set names utf8mb4;
